In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
import gmaps

# Census & gmaps API Keys
from config import (api_key, gkey)
c = Census(api_key, year=2019)

# Configure gmaps
gmaps.configure(api_key=gkey)

In [2]:
# Run Census Search to retrieve data on all states
# Note the addition of "B23025_005E" for unemployment count
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E",
                          "B23025_005E"), {'for': 'state:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "B23025_005E": "Unemployment Count",
                                      "NAME": "Name", "state": "State"})

# Add in Poverty Rate (Poverty Count / Population)
census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Add in Employment Rate (Employment Count / Population)
census_pd["Unemployment Rate"] = 100 * \
    census_pd["Unemployment Count"].astype(
        int) / census_pd["Population"].astype(int)

# Final DataFrame
census_pd = census_pd[["State", "Name", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count", "Poverty Rate", "Unemployment Rate"]]

census_pd.head()

,State,Name,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Unemployment Rate
0,01,Alabama,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,2.708946
1,02,Alaska,737068.0,34.3,77640.0,36787.0,76933.0,10.437707,3.637114
2,04,Arizona,7050299.0,37.7,58945.0,30694.0,1043764.0,14.804535,2.778676
3,05,Arkansas,2999370.0,38.1,47597.0,26577.0,496260.0,16.545475,2.349860
4,06,California,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,3.052765

In [4]:
census_data

[{'NAME': 'Alabama',
  'B19013_001E': 50536.0,
  'B01003_001E': 4876250.0,
  'B01002_001E': 39.0,
  'B19301_001E': 27928.0,
  'B17001_002E': 795989.0,
  'B23025_005E': 132095.0,
  'state': '01'},
 {'NAME': 'Alaska',
  'B19013_001E': 77640.0,
  'B01003_001E': 737068.0,
  'B01002_001E': 34.3,
  'B19301_001E': 36787.0,
  'B17001_002E': 76933.0,
  'B23025_005E': 26808.0,
  'state': '02'},
 {'NAME': 'Arizona',
  'B19013_001E': 58945.0,
  'B01003_001E': 7050299.0,
  'B01002_001E': 37.7,
  'B19301_001E': 30694.0,
  'B17001_002E': 1043764.0,
  'B23025_005E': 195905.0,
  'state': '04'},
 {'NAME': 'Arkansas',
  'B19013_001E': 47597.0,
  'B01003_001E': 2999370.0,
  'B01002_001E': 38.1,
  'B19301_001E': 26577.0,
  'B17001_002E': 496260.0,
  'B23025_005E': 70481.0,
  'state': '05'},
 {'NAME': 'California',
  'B19013_001E': 75235.0,
  'B01003_001E': 39283497.0,
  'B01002_001E': 36.5,
  'B19301_001E': 36955.0,
  'B17001_002E': 5149742.0,
  'B23025_005E': 1199233.0,
  'state': '06'},
 {'NAME': 'Colorado',
  'B19013_001E': 72331.0,
  'B01003_001E': 5610349.0,
  'B01002_001E': 36.7,
  'B19301_001E': 38226.0,
  'B17001_002E': 565873.0,
  'B23025_005E': 131371.0,
  'state': '08'},
 {'NAME': 'Delaware',
  'B19013_001E': 68287.0,
  'B01003_001E': 957248.0,
  'B01002_001E': 40.6,
  'B19301_001E': 35450.0,
  'B17001_002E': 109400.0,
  'B23025_005E': 26481.0,
  'state': '10'},
 {'NAME': 'District of Columbia',
  'B19013_001E': 86420.0,
  'B01003_001E': 692683.0,
  'B01002_001E': 34.0,
  'B19301_001E': 56147.0,
  'B17001_002E': 107140.0,
  'B23025_005E': 27967.0,
  'state': '11'},
 {'NAME': 'Connecticut',
  'B19013_001E': 78444.0,
  'B01003_001E': 3575074.0,
  'B01002_001E': 41.0,
  'B19301_001E': 44496.0,
  'B17001_002E': 344146.0,
  'B23025_005E': 116456.0,
  'state': '09'},
 {'NAME': 'Florida',
  'B19013_001E': 55660.0,
  'B01003_001E': 20901636.0,
  'B01002_001E': 42.0,
  'B19301_001E': 31619.0,
  'B17001_002E': 2870487.0,
  'B23025_005E': 561448.0,
  'state': '12'},
 {'NAME': 'Georgia',
  'B19013_001E': 58700.0,
  'B01003_001E': 10403847.0,
  'B01002_001E': 36.7,
  'B19301_001E': 31067.0,
  'B17001_002E': 1528558.0,
  'B23025_005E': 290560.0,
  'state': '13'},
 {'NAME': 'Idaho',
  'B19013_001E': 55785.0,
  'B01003_001E': 1717750.0,
  'B01002_001E': 36.4,
  'B19301_001E': 27970.0,
  'B17001_002E': 221256.0,
  'B23025_005E': 35879.0,
  'state': '16'},
 {'NAME': 'Hawaii',
  'B19013_001E': 81275.0,
  'B01003_001E': 1422094.0,
  'B01002_001E': 39.1,
  'B19301_001E': 35567.0,
  'B17001_002E': 130649.0,
  'B23025_005E': 30269.0,
  'state': '15'},
 {'NAME': 'Illinois',
  'B19013_001E': 65886.0,
  'B01003_001E': 12770631.0,
  'B01002_001E': 38.1,
  'B19301_001E': 36038.0,
  'B17001_002E': 1557873.0,
  'B23025_005E': 394981.0,
  'state': '17'},
 {'NAME': 'Indiana',
  'B19013_001E': 56303.0,
  'B01003_001E': 6665703.0,
  'B01002_001E': 37.7,
  'B19301_001E': 29777.0,
  'B17001_002E': 867996.0,
  'B23025_005E': 161351.0,
  'state': '18'},
 {'NAME': 'Iowa',
  'B19013_001E': 60523.0,
  'B01003_001E': 3139508.0,
  'B01002_001E': 38.2,
  'B19301_001E': 32176.0,
  'B17001_002E': 348122.0,
  'B23025_005E': 62573.0,
  'state': '19'},
 {'NAME': 'Kansas',
  'B19013_001E': 59597.0,
  'B01003_001E': 2910652.0,
  'B01002_001E': 36.7,
  'B19301_001E': 31814.0,
  'B17001_002E': 337739.0,
  'B23025_005E': 61002.0,
  'state': '20'},
 {'NAME': 'Kentucky',
  'B19013_001E': 50589.0,
  'B01003_001E': 4449052.0,
  'B01002_001E': 38.9,
  'B19301_001E': 28178.0,
  'B17001_002E': 747010.0,
  'B23025_005E': 116945.0,
  'state': '21'},
 {'NAME': 'Louisiana',
  'B19013_001E': 49469.0,
  'B01003_001E': 4664362.0,
  'B01002_001E': 36.9,
  'B19301_001E': 27923.0,
  'B17001_002E': 871467.0,
  'B23025_005E': 141020.0,
  'state': '22'},
 {'NAME': 'Maine',
  'B19013_001E': 57918.0,
  'B01003_001E': 1335492.0,
  'B01002_001E': 44.7,
  'B19301_001E': 32637.0,
  'B17001_002E': 153131.0,
  'B23025_005E': 28922.0,
  'state': '23'},
 {'NAME': 'Maryland',
  'B19013_001E': 84805.0,
  'B01003_001E': 6018848.0,
  'B01002_001E': 38.7,
  'B19301_001E': 42122.0,
  'B17001_002E': 539991.0,
  'B23025_005E': 164396.0,
  'state': '24'},
 {'NAME': 'Massachusetts',
  'B19013_001E': 81215.0,
  'B01003_001E': 6850553.0,
  'B01002_001E': 39.5,
  'B19301_001E': 43761.0,
  'B17001_002E': 680962.0,
  'B23025_005E': 183355.0,
  'state': '25'},
 {'NAME': 'Michigan',
  'B19013_001E': 57144.0,
  'B01003_001E': 9965265.0,
  'B01002_001E': 39.7,
  'B19301_001E': 31713.0,
  'B17001_002E': 1398527.0,
  'B23025_005E': 293894.0,
  'state': '26'},
 {'NAME': 'Minnesota',
  'B19013_001E': 71306.0,
  'B01003_001E': 5563378.0,
  'B01002_001E': 38.0,
  'B19301_001E': 37625.0,
  'B17001_002E': 526065.0,
  'B23025_005E': 111115.0,
  'state': '27'},
 {'NAME': 'Mississippi',
  'B19013_001E': 45081.0,
  'B01003_001E': 2984418.0,
  'B01002_001E': 37.5,
  'B19301_001E': 24369.0,
  'B17001_002E': 585786.0,
  'B23025_005E': 99733.0,
  'state': '28'},
 {'NAME': 'Missouri',
  'B19013_001E': 55461.0,
  'B01003_001E': 6104910.0,
  'B01002_001E': 38.6,
  'B19301_001E': 30810.0,
  'B17001_002E': 810045.0,
  'B23025_005E': 139789.0,
  'state': '29'},
 {'NAME': 'Montana',
  'B19013_001E': 54970.0,
  'B01003_001E': 1050649.0,
  'B01002_001E': 39.9,
  'B19301_001E': 31151.0,
  'B17001_002E': 134605.0,
  'B23025_005E': 21513.0,
  'state': '30'},
 {'NAME': 'Nebraska',
  'B19013_001E': 61439.0,
  'B01003_001E': 1914571.0,
  'B01002_001E': 36.5,
  'B19301_001E': 32302.0,
  'B17001_002E': 206579.0,
  'B23025_005E': 34535.0,
  'state': '31'},
 {'NAME': 'Nevada',
  'B19013_001E': 60365.0,
  'B01003_001E': 2972382.0,
  'B01002_001E': 38.0,
  'B19301_001E': 31557.0,
  'B17001_002E': 384690.0,
  'B23025_005E': 92426.0,
  'state': '32'},
 {'NAME': 'New Hampshire',
  'B19013_001E': 76768.0,
  'B01003_001E': 1348124.0,
  'B01002_001E': 42.9,
  'B19301_001E': 40003.0,
  'B17001_002E': 98682.0,
  'B23025_005E': 27430.0,
  'state': '33'},
 {'NAME': 'New Jersey',
  'B19013_001E': 82545.0,
  'B01003_001E': 8878503.0,
  'B01002_001E': 39.9,
  'B19301_001E': 42745.0,
  'B17001_002E': 869081.0,
  'B23025_005E': 258093.0,
  'state': '34'},
 {'NAME': 'New Mexico',
  'B19013_001E': 49754.0,
  'B01003_001E': 2092454.0,
  'B01002_001E': 37.8,
  'B19301_001E': 27230.0,
  'B17001_002E': 392065.0,
  'B23025_005E': 63458.0,
  'state': '35'},
 {'NAME': 'New York',
  'B19013_001E': 68486.0,
  'B01003_001E': 19572319.0,
  'B01002_001E': 38.8,
  'B19301_001E': 39326.0,
  'B17001_002E': 2681277.0,
  'B23025_005E': 547509.0,
  'state': '36'},
 {'NAME': 'North Carolina',
  'B19013_001E': 54602.0,
  'B01003_001E': 10264876.0,
  'B01002_001E': 38.7,
  'B19301_001E': 30783.0,
  'B17001_002E': 1467591.0,
  'B23025_005E': 281344.0,
  'state': '37'},
 {'NAME': 'North Dakota',
  'B19013_001E': 64894.0,
  'B01003_001E': 756717.0,
  'B01002_001E': 35.1,
  'B19301_001E': 36062.0,
  'B17001_002E': 78198.0,
  'B23025_005E': 11406.0,
  'state': '38'},
 {'NAME': 'Ohio',
  'B19013_001E': 56602.0,
  'B01003_001E': 11655397.0,
  'B01002_001E': 39.4,
  'B19301_001E': 31552.0,
  'B17001_002E': 1588343.0,
  'B23025_005E': 314483.0,
  'state': '39'},
 {'NAME': 'Oklahoma',
  'B19013_001E': 52919.0,
  'B01003_001E': 3932870.0,
  'B01002_001E': 36.6,
  'B19301_001E': 28422.0,
  'B17001_002E': 598373.0,
  'B23025_005E': 94834.0,
  'state': '40'},
 {'NAME': 'Oregon',
  'B19013_001E': 62818.0,
  'B01003_001E': 4129803.0,
  'B01002_001E': 39.3,
  'B19301_001E': 33763.0,
  'B17001_002E': 533527.0,
  'B23025_005E': 114559.0,
  'state': '41'},
 {'NAME': 'Pennsylvania',
  'B19013_001E': 61744.0,
  'B01003_001E': 12791530.0,
  'B01002_001E': 40.8,
  'B19301_001E': 34352.0,
  'B17001_002E': 1539183.0,
  'B23025_005E': 347378.0,
  'state': '42'},
 {'NAME': 'Rhode Island',
  'B19013_001E': 67167.0,
  'B01003_001E': 1057231.0,
  'B01002_001E': 39.9,
  'B19301_001E': 36121.0,
  'B17001_002E': 125826.0,
  'B23025_005E': 30455.0,
  'state': '44'},
 {'NAME': 'South Carolina',
  'B19013_001E': 53199.0,
  'B01003_001E': 5020806.0,
  'B01002_001E': 39.4,
  'B19301_001E': 29426.0,
  'B17001_002E': 741650.0,
  'B23025_005E': 139526.0,
  'state': '45'},
 {'NAME': 'South Dakota',
  'B19013_001E': 58275.0,
  'B01003_001E': 870638.0,
  'B01002_001E': 37.0,
  'B19301_001E': 30773.0,
  'B17001_002E': 110553.0,
  'B23025_005E': 15736.0,
  'state': '46'},
 {'NAME': 'Tennessee',
  'B19013_001E': 53320.0,
  'B01003_001E': 6709356.0,
  'B01002_001E': 38.7,
  'B19301_001E': 29859.0,
  'B17001_002E': 996930.0,
  'B23025_005E': 172799.0,
  'state': '47'},
 {'NAME': 'Texas',
  'B19013_001E': 61874.0,
  'B01003_001E': 28260856.0,
  'B01002_001E': 34.6,
  'B19301_001E': 31277.0,
  'B17001_002E': 4072194.0,
  'B23025_005E': 708827.0,
  'state': '48'},
 {'NAME': 'Vermont',
  'B19013_001E': 61973.0,
  'B01003_001E': 624313.0,
  'B01002_001E': 42.9,
  'B19301_001E': 34577.0,
  'B17001_002E': 65652.0,
  'B23025_005E': 12323.0,
  'state': '50'},
 {'NAME': 'Utah',
  'B19013_001E': 71621.0,
  'B01003_001E': 3096848.0,
  'B01002_001E': 30.8,
  'B19301_001E': 29775.0,
  'B17001_002E': 298537.0,
  'B23025_005E': 55539.0,
  'state': '49'},
 {'NAME': 'Virginia',
  'B19013_001E': 74222.0,
  'B01003_001E': 8454463.0,
  'B01002_001E': 38.2,
  'B19301_001E': 39278.0,
  'B17001_002E': 865691.0,
  'B23025_005E': 200850.0,
  'state': '51'},
 {'NAME': 'Washington',
  'B19013_001E': 73775.0,
  'B01003_001E': 7404107.0,
  'B01002_001E': 37.7,
  'B19301_001E': 38915.0,
  'B17001_002E': 785244.0,
  'B23025_005E': 187330.0,
  'state': '53'},
 {'NAME': 'West Virginia',
  'B19013_001E': 46711.0,
  'B01003_001E': 1817305.0,
  'B01002_001E': 42.5,
  'B19301_001E': 26480.0,
  'B17001_002E': 310044.0,
  'B23025_005E': 51910.0,
  'state': '54'},
 {'NAME': 'Wisconsin',
  'B19013_001E': 61747.0,
  'B01003_001E': 5790716.0,
  'B01002_001E': 39.5,
  'B19301_001E': 33375.0,
  'B17001_002E': 639160.0,
  'B23025_005E': 111564.0,
  'state': '55'},
 {'NAME': 'Wyoming',
  'B19013_001E': 64049.0,
  'B01003_001E': 581024.0,
  'B01002_001E': 37.7,
  'B19301_001E': 33366.0,
  'B17001_002E': 62257.0,
  'B23025_005E': 13544.0,
  'state': '56'},
 {'NAME': 'Puerto Rico',
  'B19013_001E': 20539.0,
  'B01003_001E': 3318447.0,
  'B01002_001E': 41.7,
  'B19301_001E': 12914.0,
  'B17001_002E': 1449091.0,
  'B23025_005E': 196934.0,
  'state': '72'}]

In [3]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_pd.to_csv("census_data_states.csv", encoding="utf-8", index=False)

PermissionError: [Errno 13] Permission denied: 'census_data_states.csv'